### ISSUE TITLE
Rust meetups does not contain KL

### ISSUE THREAD

**Issue by pickfire** [szabgab/rust.code-maven.com#9]
This week in rust meetups, our group from Kuala Lumpur, Malaysia does host it but I don't see it in the list scraped.

**Comment by szabgab** [comment]
I am sure there are others missing too.
You can send a pull-request to add it. Or at least you can include a link to it here so I can add it.

**Comment by pickfire** [comment]
I didn't dig deep where to check. The details are available at https://rust-malaysia.github.io/meetup/

**Comment by szabgab** [comment]
Thanks. Added
